version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"
    depends_on:
      - mysql

  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    environment:
        - DJANGO_SETTINGS_MODULE=backend.settings
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py custom_migrate &&
            python manage.py populate_db && 
            uvicorn backend.asgi:application --host 0.0.0.0 --reload"
    volumes:
      - ./backend:/app
    depends_on:
      - mysql
    ports:
      - "8000:8000"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672" # RabbitMQ server
      - "15672:15672" # Management interface
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  mysql-data:
  rabbitmq-data:
